<?php

/**
 * @file
 * Contains utils.module.
 */

use Drupal\commerce_product\Entity\Product;
use Drupal\Core\Access\AccessResult;
use Drupal\flag\Entity\Flag;
use Drupal\flag\FlagInterface;
use Drupal\paragraphs\Entity\Paragraph;
use Drupal\user\Entity\User;
use Drupal\user\UserInterface;
use Drupal\webform\WebformSubmissionInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_cron().
 *
 * Deactivates all purchased courses when time is up.
 */
function utils_cron() {
  $storage = \Drupal::entityTypeManager()->getStorage('paragraph');
  $results = $storage->loadByProperties([
    'type' => 'activated_course',
  ]);
  foreach ($results as $result) {
    if (!($result instanceof Paragraph)) {
      return;
    }
    $duration = strtotime($result->get('field_duration')->value);
    $now = \Drupal::time()->getCurrentTime();

    if ($duration &&
        $duration <= $now
    ) {
      $product_id = $result->get('field_course')->target_id;
      $product = Product::load($product_id);
      $flag = Flag::load('activate_course');
      $flag_service = \Drupal::service('flag');
      $current_user = User::load($result->get('field_user')->target_id);

      if ($flag instanceof FlagInterface &&
        !$current_user->isAnonymous() &&
        $flag->isFlagged($product, $current_user)
      ) {
        $flag_service->unflag($flag, $product, $current_user);
      }
    }
  }
}

/**
 * Custom callback to access 'view.purchased_courses.purchased_courses'.
 */
function utils_access_callback_customer_role() {
  $access = FALSE;
  $user = \Drupal::routeMatch()->getParameter('user');
  $current_user = \Drupal::currentUser();

  if ($current_user->hasPermission('access toolbar')) {
    return AccessResult::allowed();
  }

  elseif ($user instanceof UserInterface &&
      $user->id() === $current_user->id()
  ) {
    $access = TRUE;
  }

  elseif ($user === $current_user->id()) {
    $access = TRUE;
  }

  return AccessResult::allowedIf($access);
}

/**
 * Implements hook_file_access().
 *
 * Redirect to form if user does not sign agreement to download book.
 */
function utils_file_access(
  $file,
  $op,
  $account,
) {
  $product_id = \Drupal::entityQuery('commerce_product_variation')
    ->condition('field_file.target_id', $file->id())
    ->accessCheck(FALSE)
    ->execute();

  if ($op == 'download' &&
      !empty($product_id)
  ) {
    $product_id = reset($product_id);

    $query = \Drupal::service('webform_query');
    $query->setWebform('download_book')
      ->addCondition('product', $product_id)
      ->addCondition('user', $account->id())
      ->addCondition('eula', '1');
    $result = $query->execute();

    if (empty($result)) {
      \Drupal::messenger()
        ->addError(t('You must agree to the terms before downloading the book.'));
      $token = \Drupal::service('uuid')->generate();
      $store = \Drupal::service('tempstore.private')->get('utils');
      $store->set($token, $product_id);
      $response = new RedirectResponse("/∂token=$token");
      $response->send();
      exit;
    }
  }

  return AccessResult::neutral();
}

/**
 * Implements hook_ENTITY_TYPE_presave() for webform_submission entities.
 */
function utils_webform_submission_presave(
  WebformSubmissionInterface $webform_submission,
) {
  $request = \Drupal::request();
  $token = $request->query->get('token');
  if ($webform_submission->getWebform()->id() === 'download_book' &&
      $token
  ) {
    $store = \Drupal::service('tempstore.private')->get('utils');
    $data = $webform_submission->getData();
    $product_id = $store->get($token);
    $data['product'] = $product_id;
    $store->delete($token);
    $webform_submission->setData($data);
  }
}
